name: Render README.md

on:
  push:
    paths:
      - 'members'
      - '.github/workflows/render.yml'
      - '.github/scripts/render.py'
      - '.github/scripts/template.md'

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master
    - name: setup Python
      uses: actions/setup-python@v3.1.0
      with:
        python-version: 3.9
    - name: render README.md
      run: |
        python .github/scripts/render.py
    - name: commit changes
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git diff-index --quiet HEAD || git commit -m "render README.md"
    - name: push changes
      uses: CasperWA/push-protected@v2
      with:
        github_token: ${{ secrets.ACCESS_TOKEN }}
        branch: ${{ github.ref }}

  